
services:
  ...
  
  nginx:
    container_name: nginx
    command: nginx -g 'daemon off;'
    depends_on:
      - app   #django
    image: nginx:latest
    networks:
      - main
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf


networks:
  main:
